site_name: CoCoNuT
repo_url: https://github.com/pyfsi/coconut
edit_uri: ''
site_description: site_description
theme:
    name: 'material'
    logo: 'images/logo.png'
    feature:
        tabs: true
    favicon: 'assets/images/favicon.ico'
    palette:
        primary: 'green'
        accent: 'green'
markdown_extensions:
    - codehilite
    - pymdownx.arithmatex
extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
nav:
    - README.md
    - CouplingComponents:
        - CoupledSolvers:
            - coupled_solvers.md
            - models.md
        - Predictors: predictors.md
        - ConvergenceCriteria: convergence_criteria.md
        - SolverWrappers:
            - fluent.md
            - abaqus.md
            - python.md
        - Mappers: mappers.md
    - TestExamples:
        - TestExample: test_examples.md
        - Tube:
            - Fluent 2D - Abaqus 2D: tube_fluent2d_abaqus2d.md
            - Fluent 2D - Python: tube_fluent2d_tube_structure.md
            - Fluent 3D - Abaqus 3D: tube_fluent3d_abaqus3d.md
            - Fluent 3D - Abaqus 2D: tube_fluent3d_abaqus2d.md
            - Python TubeFlow - Abaqus 2D: tube_tube_flow_abaqus2d.md
            - Python TubeFlow - Python TubeRingmodel: tube_tube_flow_tube_ringmodel.md
            - Python TubeFlow - Python TubeStructre: tube_tube_flow_tube_structure.md
    - Varia:
        - data_structure.md
        - docs.md
